# Lab 4 Multi-variable linear regression

In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [2]:
# x : mid ex
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
# y : final ex
y_data = [152., 185., 180., 196., 142.]

placeholders for a tensor that will be always fed.

In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [4]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [5]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
print(hypothesis)

Tensor("add_2:0", dtype=float32)


cost/loss function

In [6]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

Minimize. Need a very small learning rate for this data set

In [8]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  62547.3 
Prediction:
 [-75.96344757 -78.27629089 -83.83014679 -90.80435944 -56.97648239]
100 Cost:  13.2472 
Prediction:
 [ 146.06376648  188.31446838  178.98654175  195.37893677  146.31259155]
200 Cost:  12.5621 
Prediction:
 [ 146.20278931  188.21931458  179.02929688  195.40849304  146.18890381]
300 Cost:  11.9133 
Prediction:
 [ 146.33810425  188.12670898  179.07095337  195.43722534  146.068573  ]
400 Cost:  11.2986 
Prediction:
 [ 146.4697876   188.0365448   179.11146545  195.46513367  145.95143127]
500 Cost:  10.7164 
Prediction:
 [ 146.59799194  187.94880676  179.15092468  195.49229431  145.83746338]
600 Cost:  10.1648 
Prediction:
 [ 146.72277832  187.86340332  179.18934631  195.51869202  145.7265625 ]
700 Cost:  9.64238 
Prediction:
 [ 146.84425354  187.7802887   179.22674561  195.54437256  145.61865234]
800 Cost:  9.14744 
Prediction:
 [ 146.96246338  187.69935608  179.26315308  195.56930542  145.51361084]
900 Cost:  8.6786 
Prediction:
 [ 147.07757568  187.62060547  

---

input data as matrix

In [10]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [15]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3]) # 대충 몇개다 : None
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [16]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [17]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [18]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  22712.4 
Prediction:
 [[ 15.35308552]
 [ 25.62049103]
 [ 21.43587303]
 [ 23.02159691]
 [ 21.90162849]]
100 Cost:  3.20764 
Prediction:
 [[ 149.13404846]
 [ 186.28488159]
 [ 179.80903625]
 [ 195.4785614 ]
 [ 144.42182922]]
200 Cost:  3.04557 
Prediction:
 [[ 149.20123291]
 [ 186.23880005]
 [ 179.82958984]
 [ 195.49372864]
 [ 144.36109924]]
300 Cost:  2.89204 
Prediction:
 [[ 149.26663208]
 [ 186.19395447]
 [ 179.84957886]
 [ 195.50846863]
 [ 144.30198669]]
400 Cost:  2.7466 
Prediction:
 [[ 149.33027649]
 [ 186.15028381]
 [ 179.86903381]
 [ 195.52285767]
 [ 144.24446106]]
500 Cost:  2.60886 
Prediction:
 [[ 149.39219666]
 [ 186.10780334]
 [ 179.88796997]
 [ 195.53684998]
 [ 144.1884613 ]]
600 Cost:  2.47837 
Prediction:
 [[ 149.45246887]
 [ 186.06645203]
 [ 179.90640259]
 [ 195.55047607]
 [ 144.13395691]]
700 Cost:  2.35478 
Prediction:
 [[ 149.51112366]
 [ 186.0262146 ]
 [ 179.92434692]
 [ 195.56370544]
 [ 144.08091736]]
800 Cost:  2.23769 
Prediction:
 [[ 149.56820679]
 [ 185

---

# how to import data

In [20]:
import numpy as np

In [23]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
xy

array([[  73.,   80.,   75.,  152.],
       [  93.,   88.,   93.,  185.],
       [  89.,   91.,   90.,  180.],
       [  96.,   98.,  100.,  196.],
       [  73.,   66.,   70.,  142.],
       [  53.,   46.,   55.,  101.],
       [  69.,   74.,   77.,  149.],
       [  47.,   56.,   60.,  115.],
       [  87.,   79.,   90.,  175.],
       [  79.,   70.,   88.,  164.],
       [  69.,   70.,   73.,  141.],
       [  70.,   65.,   74.,  141.],
       [  93.,   95.,   91.,  184.],
       [  79.,   80.,   73.,  152.],
       [  70.,   73.,   78.,  148.],
       [  93.,   89.,   96.,  192.],
       [  78.,   75.,   68.,  147.],
       [  81.,   90.,   93.,  183.],
       [  88.,   92.,   86.,  177.],
       [  78.,   83.,   77.,  159.],
       [  82.,   86.,   90.,  177.],
       [  86.,   82.,   89.,  175.],
       [  78.,   83.,   85.,  175.],
       [  76.,   83.,   71.,  149.],
       [  96.,   93.,   95.,  192.]], dtype=float32)

In [24]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [25]:
# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 25
(25, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]


In [26]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [27]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [28]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [29]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  10808.6 
Prediction:
 [[ 251.09085083]
 [ 301.1428833 ]
 [ 296.89666748]
 [ 325.21548462]
 [ 227.97183228]
 [ 170.902771  ]
 [ 246.41296387]
 [ 186.85440063]
 [ 283.58547974]
 [ 266.76095581]
 [ 235.29014587]
 [ 232.43911743]
 [ 304.79696655]
 [ 250.6489563 ]
 [ 247.65771484]
 [ 307.43710327]
 [ 236.23348999]
 [ 297.04751587]
 [ 290.38162231]
 [ 260.23590088]
 [ 288.19338989]
 [ 284.38858032]
 [ 274.29000854]
 [ 248.67144775]
 [ 311.31192017]]
100 Cost:  7.55182 
Prediction:
 [[ 153.37205505]
 [ 183.71385193]
 [ 181.1831665 ]
 [ 199.17666626]
 [ 138.43284607]
 [ 104.86376953]
 [ 152.03604126]
 [ 116.84312439]
 [ 173.82226562]
 [ 165.05543518]
 [ 144.38729858]
 [ 142.80888367]
 [ 185.26777649]
 [ 151.31236267]
 [ 152.84797668]
 [ 188.25523376]
 [ 141.65652466]
 [ 183.77000427]
 [ 176.42744446]
 [ 158.26860046]
 [ 177.53079224]
 [ 174.20552063]
 [ 168.78536987]
 [ 150.19117737]
 [ 189.61573792]]
200 Cost:  7.4734 
Prediction:
 [[ 153.37026978]
 [ 183.73199463]
 [ 181.19203186]
 

In [32]:
# Ask my score
print("Your score will be ", sess.run(
    hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[ 184.67326355]]
Other scores will be  [[ 187.96507263]
 [ 174.46272278]]


---

# Queue Runners

In [33]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

In [34]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

data type

In [35]:
# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

batch

In [36]:
# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

In [37]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [38]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [39]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [40]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

0 Cost:  10982.9 
Prediction:
 [[ 51.74819565]
 [ 62.83285141]
 [ 61.42819977]
 [ 66.74022675]
 [ 48.58052063]
 [ 36.37724686]
 [ 50.10719681]
 [ 37.16603851]
 [ 59.05656052]
 [ 54.90377426]]
100 Cost:  6.51679 
Prediction:
 [[ 153.86054993]
 [ 185.62568665]
 [ 182.38124084]
 [ 198.51812744]
 [ 142.20376587]
 [ 105.4876709 ]
 [ 148.8054657 ]
 [ 110.41400146]
 [ 173.89198303]
 [ 161.38737488]]
200 Cost:  6.33336 
Prediction:
 [[ 153.82461548]
 [ 185.62245178]
 [ 182.35379028]
 [ 198.53318787]
 [ 142.17410278]
 [ 105.53979492]
 [ 148.87236023]
 [ 110.54018402]
 [ 173.95315552]
 [ 161.54696655]]
300 Cost:  6.16688 
Prediction:
 [[ 153.79086304]
 [ 185.61859131]
 [ 182.32756042]
 [ 198.54779053]
 [ 142.14463806]
 [ 105.58893585]
 [ 148.93716431]
 [ 110.66249084]
 [ 174.01080322]
 [ 161.69903564]]
400 Cost:  6.01576 
Prediction:
 [[ 153.75921631]
 [ 185.61418152]
 [ 182.30249023]
 [ 198.56196594]
 [ 142.11535645]
 [ 105.63520813]
 [ 148.99998474]
 [ 110.78105164]
 [ 174.06510925]
 [ 161.843

In [41]:
# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[ 187.02101135]]
Other scores will be  [[ 171.65446472]
 [ 177.97869873]]


shuffle_batch

In [43]:
min_after_dequeue = 10
batch_size = 5
capacity = min_after_dequeue + 3 * batch_size

In [44]:
example_batch, label_batch = tf.train.shuffle_batchu(
[example, label], batch_size = batch_size, capacity = capacity,
min_after_dequeue = min_after_dequeue)

AttributeError: module 'tensorflow.python.training.training' has no attribute 'shuffle_batchu'